src/model/entity/Author.java
package model.entity;

import java.io.Serializable;
import javax.persistence.*;
import java.util.Date;
import java.util.List;

@Entity
@Table(name="Authors")
@NamedQuery(name="Author.findAll", query="SELECT a FROM Author a")
public class Author implements Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(unique=true, nullable=false)
	private int id;

	@Temporal(TemporalType.DATE)
	private Date birthDate;

	@Temporal(TemporalType.DATE)
	private Date dateOfDeath;

	@Column(nullable=false, length=20)
	private String firstName;

	@Column(length=50)
	private String interest;

	@Column(nullable=false, length=20)
	private String lastName;

	@Column(length=20)
	private String nationality;

	//bi-directional many-to-one association to Authors_Genre
	@OneToMany(mappedBy="author")
	private List<Authors_Genre> authorsGenres;

	//bi-directional many-to-one association to Authorship
	@OneToMany(mappedBy="author")
	private List<Authorship> authorships;

	public Author() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Date getDateOfDeath() {
		return dateOfDeath;
	}

	public void setDateOfDeath(Date dateOfDeath) {
		this.dateOfDeath = dateOfDeath;
	}
	
	public String getFullName(){
		return firstName + " " + lastName;
	}
	
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getInterest() {
		return interest;
	}

	public void setInterest(String interest) {
		this.interest = interest;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public List<Authors_Genre> getAuthorsGenres() {
		return authorsGenres;
	}

	public void setAuthorsGenres(List<Authors_Genre> authorsGenres) {
		this.authorsGenres = authorsGenres;
	}

	public Authors_Genre addAuthorsGenre(Authors_Genre authorsGenre) {
		getAuthorsGenres().add(authorsGenre);
		authorsGenre.setAuthor(this);

		return authorsGenre;
	}

	public Authors_Genre removeAuthorsGenre(Authors_Genre authorsGenre) {
		getAuthorsGenres().remove(authorsGenre);
		authorsGenre.setAuthor(null);

		return authorsGenre;
	}

	public List<Authorship> getAuthorships() {
		return this.authorships;
	}

	public void setAuthorships(List<Authorship> authorships) {
		this.authorships = authorships;
	}

	public Authorship addAuthorship(Authorship authorship) {
		getAuthorships().add(authorship);
		authorship.setAuthor(this);

		return authorship;
	}

	public Authorship removeAuthorship(Authorship authorship) {
		getAuthorships().remove(authorship);
		authorship.setAuthor(null);

		return authorship;
	}

}

src/controllers/ReservationController.java
package controllers;

import java.io.Serializable;
import java.sql.Date;
import java.util.Calendar;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import controllers.users.PersonController;
import model.beans.ReservationBean;
import model.beans.login.Account;
import model.entity.Copy;
import model.entity.Person;
import model.entity.Reservation;
import model.entity.Title;
import model.jpaejb.BorrowingFacade;
import model.jpaejb.ReservationFacade;
import model.jpaejb.TitleFacade;

@Named
@SessionScoped
public class ReservationController implements Serializable {
	@EJB
	ReservationFacade reservationFacade;
	
	@EJB
	TitleFacade titleFacade;
	
	@EJB
	BorrowingFacade borrowingFacade;
	
	@Inject
	ReservationBean reservationBean;
	
	@Inject
	Account accountBean;
	
	@Inject
	PersonController personController;
	
	private static final long serialVersionUID = 1L;
	
	public List<Reservation> getAll() {
		return reservationFacade.findAll();
	}
	
	public List<Reservation> getMyReservations() {
		Person person = personController.getLoggedPerson();
		
		return getPersonReservations(person);
	}
	
	public int count() {
		return reservationFacade.count();
	}
	
	public void delete(Reservation reservation) {
		reservationFacade.remove(reservation);
	}
	
	public void deletem(Title title) {
		Person person = personController.getLoggedPerson();
		List<Reservation> userReservations = getPersonReservations(person, title);
		
		reservationFacade.remove(userReservations.get(0));
	}
	
	/**
	 * Add reservation for 3 days.
	 * 
	 * @param title Which title you want to reserve.
	 */
	public void add(Title title) {
		Reservation reservation = new Reservation();
		
		if(isTitleAvaible(title)) {
			// Get actual logged person (reader)
			reservation.setPerson(personController.getLoggedPerson());
			
			// Get actaul date a set it as reserve since
			Calendar calendar = Calendar.getInstance();
			reservation.setReserveSince(new Date(calendar.getTime().getTime()));
			
			// Set reservation for three days
			calendar.add(Calendar.DAY_OF_YEAR, 3);
			reservation.setReserveTo(new Date(calendar.getTime().getTime()));
			
			reservation.setTitle(title);
			
			reservationFacade.create(reservation);
			
			title.addReservation(reservation);
			
			titleFacade.edit(title);
		}
		
	}
	
	/**
	 * 
	 * @param title
	 * 
	 * @return true if title has reservations.
	 */
	public boolean hasReserve(Title title) {
		Person loggedUser = personController.getLoggedPerson();
		
		List<Reservation> userReservations = getPersonReservations(loggedUser, title);
		
		return userReservations.isEmpty() ? false : true;
	}
	
	public boolean hasNotReserved(Title title) {
		return hasReserve(title) ? false : true;
	}
	
	public String edit(Reservation reservation) {

		reservationBean.setId(reservation.getId());
		reservationBean.setPerson(reservation.getPerson());
		reservationBean.setReserveTo(reservation.getReserveTo());
		reservationBean.setTitle(reservation.getTitle());
		
		return "reservationUpdateForm";
	}

	public String save() {
		Reservation reservation = new Reservation();
		
		reservation.setId(reservationBean.getId());
		reservation.setPerson(reservationBean.getPerson());
		reservation.setReserveTo(reservationBean.getReserveTo());
		reservation.setTitle(reservationBean.getTitle());
		
		reservationFacade.edit(reservation);
		
		return "reservation";
	}
	
	public List<Reservation> getPersonReservations(Person person) {
		return reservationFacade.findMyReservations(person);
	}
	
	public List<Reservation> getPersonReservations(Person person, Title title) {
		return reservationFacade.findPersonReservations(person, title);
	}
	
	public boolean isTitleAvaible(Title title) {
		int allReservations = title.getReservations().size();
		
		List<Copy> copies= title.getCopies();
		int numOfCopies = copies.size();
		
		int avaibleCopies = numOfCopies - allReservations;
		
		boolean isBorrowed;
		for(Copy copy : copies) {
			isBorrowed = !borrowingFacade.findCopyBorrow(copy).isEmpty();
			if(isBorrowed) {
				avaibleCopies--;
			}
		}
		
		return avaibleCopies > 0 ? true : false;
	}
}

WebContent/reader/accountOverview.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Vitej knihovniku</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">
		<!-- NAVBAR -->
		<ui:include src="/reader/navbar.xhtml" />
		
		<b:container>
		
		        	
			<b:column span="4">
			
				<!-- TITLE UPDATE FORM -->
				<b:form id="titleForm" >
				
					<!-- PERSON VARIABLE -->
					<c:set var="person" value="#{personController.getLoggedPerson()}" scope="request" />
					
					<!-- OUTPUTS -->
					<p:panel id="panel" header="Moje informace" style="margin-bottom:10px;">
					    <p:messages id="messages" />
					    <h:panelGrid columns="2" cellpadding="5" style="padding-bottom:10px;" >
							
							<!-- FIRST NAME  -->
							<p:outputLabel for="firstName" value="Jméno:" />
							<p:outputLabel id="firstName" value="#{person.firstName}" />
			        	
			        		<!-- LAST NAME -->
			        		<p:outputLabel for="lastName" value="Příjmení:" />
			        		<p:outputLabel id="lastName" value="#{person.lastName}" />
	
			        		<!-- BIRTH CODE -->
			        		<p:outputLabel for="birthCode" value="Rodné číslo:" />
			        		<p:outputLabel id="birthCode" value="#{person.birthCode}" />
			        	
			        		<!-- EMAIL -->
			        		<p:outputLabel for="email" value="Email:" />
			        		<p:outputLabel id="email" value="#{person.email}" />
			        		
			        		<!-- PHONE -->
			        		<p:outputLabel for="phone" value="Mobil:" />
			        		<p:outputLabel id="phone" value="#{person.phone}" />
			        	
			        		<!-- DATE OF REGISTRATION -->
			        		<p:outputLabel for="dateRegistration" value="Datum regitrace:" />
			        		<p:outputLabel id="dateRegistration" value="#{person.dateRegistration}" />
				    			        
					    </h:panelGrid>
					</p:panel>
					
					<p:toolbar>
						<!-- BUTTONS -->
				        <f:facet name="right">
				            
				        	<!-- EDIT BUTTON -->
				        	<b:commandButton 
				        		value="Přidat" 
				        		look="success" 
				        		action="#{personController.edit(person)}" 
				        		style="margin-left: 5px;" />
				        		
				        </f:facet>
	    			</p:toolbar>
	    	
				</b:form>
			</b:column>		
		</b:container>
	</h:body>
</html>

WebContent/reader/accountUpdate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Úprava uživatele]</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">

		<!-- NAVBAR -->
		<ui:include src="/reader/navbar.xhtml" />
	
		<b:container>
			<b:column span="4">
			
				<!-- TITLE UPDATE FORM -->
				<b:form id="titleForm" >
				
					<!-- INPUTS -->
					<p:panel id="panel" header="Upravit titul" style="margin-bottom:10px;">
					    <p:messages id="messages" />
					    <h:panelGrid columns="2" cellpadding="5" style="padding-bottom:10px;">
					    
					    	<!-- FISRT NAME -->
					        <p:outputLabel for="firstName" value="Jméno:" />
					        <p:inputText id="firstName" value="#{personBean.firstName}" required="true" style="margin-top:10px;">
					            <f:validateLength minimum="2" />
					        </p:inputText>				        
					
							<!-- LAST NAME -->
					        <p:outputLabel for="lastName" value="Příjmení:" />
					        <p:inputText id="lastName" value="#{personBean.lastName}" required="true" style="margin-top:10px;"/>
					        
					        <!-- EMAIL -->
					        <p:outputLabel for="email" value="Email:" />
					        <p:inputText id="email" value="#{personBean.email}" required="true" style="margin-top:10px;"/>
					        
					        <!-- PHONE -->
					        <p:outputLabel for="phone" value="Telefon:" />
					        <p:inputText id="phone" value="#{personBean.phone}" required="true" style="margin-top:10px;"/>	
					        
					    </h:panelGrid>
					</p:panel>
					
					<p:toolbar>
						<!-- BUTTONS -->
				        <f:facet name="right">
				        
				        	<!-- BACK BUTTON -->
				            <b:commandButton
				            	value="Zpět" 
				            	look="danger" 
				            	action="#{authorController.back}" 
				            	style="margin: 5px;" 
				            	immediate="true"/>
				            
				        	<!-- ADD BUTTON -->
				            <h:commandButton
				            	look="success" 
				            	action="#{personController.save}"
				            	value="Uložit" />
				        </f:facet>
	    			</p:toolbar>
	    			
				</b:form>
			</b:column>		
		</b:container>
		
	
   
</h:body>
</html>

WebContent/reader/navbar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

	<b:navBar brand="Black Books" brandHref="readerOverview.xhtml" inverse="true"
		fixed="top">
		<b:navbarLinks>
			<b:navLink value="Moje výpůjčky" href="/blackbooks/reader/userBorrowings.xhtml?faces-redirect=true"></b:navLink>
			<b:navLink value="Moje rezervace" href="/blackbooks/reader/userReservations.xhtml?faces-redirect=true"></b:navLink>
			<b:navLink value="Správa účtu" href="/blackbooks/reader/accountOverview.xhtml?faces-redirect=true"></b:navLink>
		</b:navbarLinks>

		<h:form method="post" styleClass="navbar-form navbar-right">
                <b:commandButton action="#{accountDAO.logout}"
				value="Odhlásit se" look="success" icon="chevron-right"
				iconAlign="right" />
		</h:form>
		
	</b:navBar>
	
	<!--  SPACE -->
	<b:container>
		<b:row>
			<b:column col-md="6" col-sm="12" style="height: 50px;" />
		</b:row>
	</b:container>
</ui:composition>

WebContent/reader/readerOverview.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Vítej čtenáři</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">
	
		<!-- NAVBAR -->
		<ui:include src="navbar.xhtml" />
			
		<!--  FORM -->
	    <b:container>
			<b:column col-xs="12">
				<h:form id="findTitleForm">
				
					<!-- FIRST LINE -->
					<b:column col-xs="12">
	
						<!-- TITLE NAME -->
						<b:column col-xs="2">
						   <h:outputText value="Název:"/>
						</b:column>
						
						<b:column col-xs="4">
						    <b:inputText placeholder="" value="#{findTitleBean.title}"/>
						</b:column>
										
						<!-- ISBN -->
						<b:column col-xs="2">
					   		<h:outputText value="ISBN:"/>
						</b:column>
						
						<b:column col-xs="4">
						    <b:inputText placeholder="" value="#{findTitleBean.isbn}"/>
						</b:column>
		     		</b:column>
		         
		    		<!-- SECOND LINE -->
					<b:column col-xs="12">
					
						<!-- GENRES -->
						<b:column col-xs="2">
						   <h:outputText value="Žánr:"/>
						</b:column>
						<b:column col-xs="4">
						   <b:selectMultiMenu value="#{findTitleBean.genre}">  
							  <f:selectItems 
							  	value="#{genreController.getAll()}" 
							  	var="genre" 
							  	itemValue="#{genre.name}" 
							  	itemLabel="#{genre.name}"/>
						   </b:selectMultiMenu>
						</b:column>
											
						<!-- AUTHORS -->
						<b:column col-xs="2">
						   <h:outputText value="Autor:"/>
						</b:column>
						<b:column col-xs="4">
						   <b:selectMultiMenu value="#{findTitleBean.author}" maxHeight="500">  
							  <f:selectItems value="#{authorController.getAll()}" 
							  	var="author"
							  	itemValue="#{author.fullName}" 
							  	itemLabel="#{author.fullName}"/>
						   </b:selectMultiMenu>
						</b:column>
		     		</b:column>
		     		
		     		<!-- SPACE -->
					<b:column col-xs="12" style="height: 15px;"/>
		     		
		     		<!-- THIRD LINE -->
					<b:column col-xs="12">
					
						<!-- LANGUAGES-->
						<b:column col-xs="2">
						   <h:outputText value="Jazyk:"/>
						</b:column>
						<b:column col-xs="4">
						   <b:selectMultiMenu value="#{findTitleBean.lang}">  
							  <f:selectItem itemValue="cestina" itemLabel="čeština"/>
							  <f:selectItem itemValue="anglictina" itemLabel="angličtina"/>
						   </b:selectMultiMenu>
						</b:column>
											
						<b:column col-xs="2"/>
						<b:column col-xs="4"/>
						
		     		</b:column>
		     	
					<!-- SPACE -->
					<b:column col-xs="12" style="height: 15px;"/>			
		     		
		     		<b:column col-xs="12">
					
						<!-- FIND BUTTON -->
						<b:column col-xs="2" />
						<b:column col-xs="4">
						    <b:commandButton 
						    	update="tabbb" 
						    	icon="search" 
						    	value="Vyhledat" 
						    	look="primary" 
						    	style="width:100%" 
						    	actionListener="#{titleController.findTitles()}" />
						</b:column>
		     		</b:column>
		     		
		   		</h:form>
			 </b:column>
		</b:container>
		   	
	   	<!-- SPACE -->
		<b:column col-xs="12" style="height: 15px;"/>				
			     		
		<!-- TABLE OF TITLES -->
	 	<b:container>
	 		<b:form id="tabbb">
		  		<b:dataTable
					class="editableCarTable" 
					value="#{titleController.getFilteredTitles()}" 
					var="title" 
					searching="false" 
					responsive="true">
		  			
		  			<!-- ISBN -->
					<b:dataTableColumn label="Isbn">
	    				<h:outputText value="#{title.isbn}" />
					</b:dataTableColumn>
					
					<!-- NAME -->
					<b:dataTableColumn label="Název">
	    				<h:outputText value="#{title.name}" />
					</b:dataTableColumn>
					
					<!-- AUTHORS-->
					<b:dataTableColumn label="Autoři">
	    				<h:outputText value="#{title.authors}" />
					</b:dataTableColumn>
					
					<!-- GENRES -->
					<b:dataTableColumn label="Žánry">
	    				<h:outputText value="#{title.genres}" />
					</b:dataTableColumn>
					
					<!-- EDITION -->
					<b:dataTableColumn label="Edice">
		    				<h:outputText value="#{title.edition}" />
					</b:dataTableColumn>
					
			   		<!-- BUTTONS -->
			   		<b:dataTableColumn label="Akce" orderable="false">
	    				
	    				<!-- RESERVATION BUTTON -->
				        <b:commandButton value="Rezervovat" 
					        look="success" 
					        ajax="true" 
					        update="@(.editableCarTable)" 
					        action="#{reservationController.add(title)}"
					        rendered="#{reservationController.hasNotReserved(title)}" />
					        
					    <!-- DELETE BUTTON -->
					    <b:commandButton value="Zrušit" 
					        look="warning" 
					        ajax="true" 
					        update="@(.editableCarTable)" 
					        action="#{reservationController.deletem(title)}"
					        rendered="#{reservationController.hasReserve(title)}" />
					        
	   				</b:dataTableColumn>
	   			</b:dataTable>
			</b:form>
	    </b:container>
	    <b:messages  for="tabbb"/> 
	</h:body>
</html>

WebContent/reader/userBorrowings.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Vítej čtenáři</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">
	
		<!-- NAVBAR -->
		<ui:include src="/reader/navbar.xhtml" />
			
		<!-- TITLE TABLE LIST, EDIT, REMOVE -->
		<b:container>
			<b:form id="borrowTab">
		  		<b:dataTable
		  			class="editableCarTable" 
		  			value="#{borrowingController.getMyBorrowings()}" 
		  			var="borrowing" 
		  			searching="false" 
		  			responsive="true">
		  			
					<!-- ISBN -->
	   				 <b:dataTableColumn label="Isbn">
	    				<h:outputText value="#{borrowing.copy.title.isbn}" />
	   				 </b:dataTableColumn>
	   				
	   				<!-- TITLE NAME -->
			   		<b:dataTableColumn  label="Titul">
	    				<h:outputText value="#{borrowing.copy.title.name}" />
			   		</b:dataTableColumn>
			   		
			   		<!-- NUMBER OF COPY -->
			   		<b:dataTableColumn  label="Výtisk">
	    				<h:outputText value="#{borrowing.copy.numCopy}" />
			   		</b:dataTableColumn>
			   		
			   		<!-- BORROW TO -->
			   		<b:dataTableColumn  label="Vrátit do">
	    				<h:outputText value="#{borrowing.borrowTO}" />
			   		</b:dataTableColumn>
			   		
			   		<!-- IS RETURNED -->
					<b:dataTableColumn label="Vráceno">
      					<h:outputText value="ANO" rendered="#{borrowing.isReturn}" style="color:green;"/>
			   		</b:dataTableColumn>
				
				</b:dataTable>
			</b:form>
		</b:container>
	</h:body>
</html>

WebContent/reader/userReservations.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Moje Rezervace - Black Books</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">
		
		<!-- NAVBAR -->
		<ui:include src="/reader/navbar.xhtml" />
  		
		<!-- TABLE OF RESERVATIONS -->
	 	<b:container>
	 		<b:form id="tabbb">
		  		<b:dataTable class="editableCarTable" value="#{reservationController.myReservations}" var="reservation" searching="false" responsive="true">
		  			
		  			<!-- ISBN -->
	   				 <b:dataTableColumn >
		  				<f:facet name="header">
	      					<h:outputText value="ISBN"/>
	    				</f:facet> 
	    				<h:outputText value="#{reservation.title.isbn}" />
	   				 </b:dataTableColumn>
	   				
	   				<!-- NAME -->
			   		<b:dataTableColumn  >
			   			<f:facet name="header">
	      					<h:outputText value="Název titulu"/>
	    				</f:facet> 
	    				<h:outputText value="#{reservation.title.name}" />
			   		</b:dataTableColumn>
			   		
			   		<!-- AUTHOR -->
			   		<b:dataTableColumn>
			   			<f:facet name="header">
	      					<h:outputText value="Autor/Autoři"/>
	    				</f:facet>
				   		<ui:repeat value="#{reservation.title.authorships}" var="authorship">
						    #{authorship.author.firstName} #{authorship.author.lastName}<br/>
						</ui:repeat>
			   		</b:dataTableColumn>
	   				 
			   		
			   		<!-- RESERVE TO -->
			   		<b:dataTableColumn  >
			   			<f:facet name="header">
	      					<h:outputText value="Rezervace vyprši"/>
	    				</f:facet> 
	    				<h:outputText value="#{reservation.reserveTo}" />
			   		</b:dataTableColumn>
			   		
			   		<!-- RESERVATION -->
			   		<b:dataTableColumn orderable="false">
	   					<f:facet name="header">
	      					<h:outputText value=""/>
	    				</f:facet> 
					    <b:commandButton value="Zrušit" 
					        look="warning" 
					        ajax="true" 
					        update="@(.editableCarTable)" 
					        action="#{reservationController.deletem(reservation.title)}" />
	   				</b:dataTableColumn>
	   			</b:dataTable>
			</b:form>
	    </b:container>    
	</h:body>
</html>