src/model/entity/Author.java
package model.entity;

import java.io.Serializable;
import javax.persistence.*;
import java.util.Date;
import java.util.List;

@Entity
@Table(name="Authors")
@NamedQuery(name="Author.findAll", query="SELECT a FROM Author a")
public class Author implements Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(unique=true, nullable=false)
	private int id;

	@Temporal(TemporalType.DATE)
	private Date birthDate;

	@Temporal(TemporalType.DATE)
	private Date dateOfDeath;

	@Column(nullable=false, length=20)
	private String firstName;

	@Column(length=50)
	private String interest;

	@Column(nullable=false, length=20)
	private String lastName;

	@Column(length=20)
	private String nationality;

	//bi-directional many-to-one association to Authors_Genre
	@OneToMany(mappedBy="author")
	private List<Authors_Genre> authorsGenres;

	//bi-directional many-to-one association to Authorship
	@OneToMany(mappedBy="author")
	private List<Authorship> authorships;

	public Author() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Date getDateOfDeath() {
		return dateOfDeath;
	}

	public void setDateOfDeath(Date dateOfDeath) {
		this.dateOfDeath = dateOfDeath;
	}
	
	public String getFullName(){
		return firstName + " " + lastName;
	}
	
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getInterest() {
		return interest;
	}

	public void setInterest(String interest) {
		this.interest = interest;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public List<Authors_Genre> getAuthorsGenres() {
		return authorsGenres;
	}

	public void setAuthorsGenres(List<Authors_Genre> authorsGenres) {
		this.authorsGenres = authorsGenres;
	}

	public Authors_Genre addAuthorsGenre(Authors_Genre authorsGenre) {
		getAuthorsGenres().add(authorsGenre);
		authorsGenre.setAuthor(this);

		return authorsGenre;
	}

	public Authors_Genre removeAuthorsGenre(Authors_Genre authorsGenre) {
		getAuthorsGenres().remove(authorsGenre);
		authorsGenre.setAuthor(null);

		return authorsGenre;
	}

	public List<Authorship> getAuthorships() {
		return this.authorships;
	}

	public void setAuthorships(List<Authorship> authorships) {
		this.authorships = authorships;
	}

	public Authorship addAuthorship(Authorship authorship) {
		getAuthorships().add(authorship);
		authorship.setAuthor(this);

		return authorship;
	}

	public Authorship removeAuthorship(Authorship authorship) {
		getAuthorships().remove(authorship);
		authorship.setAuthor(null);

		return authorship;
	}

}

src/model/entity/Person.java
package model.entity;

import java.io.Serializable;

import javax.persistence.*;

import java.sql.Date;
import java.util.List;


/**
 * The persistent class for the Persons database table.
 * 
 */
@Entity
@Table(name="Persons")
@NamedQueries({
	@NamedQuery(name="Person.findAll", query="SELECT p FROM Person p"),
	@NamedQuery(name="Person.findAllReaders", query="SELECT p FROM Person p WHERE p.type='Ctenar'")
})
public class Person implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(unique=true, nullable=false, length=12)
	private String login;

	@Column(nullable=false)
	private int birthCode;

	@Column
	private Date dateRegistration;

	@Column(nullable=false, length=20)
	private String email;

	@Column(nullable=false, length=20)
	private String firstName;

	@Column(nullable=false, length=20)
	private String lastName;

	@Column(nullable=false, length=512)
	private String password;

	@Column(nullable=false, length=9)
	private String phone;

	@Column(length=10)
	private String position;

	@Column(nullable=false, length=12)
	private String type;

	//bi-directional many-to-one association to Borrowing
	@OneToMany(mappedBy="employee")
	private List<Borrowing> emplBorrows;

	//bi-directional many-to-one association to Borrowing
	@OneToMany(mappedBy="reader")
	private List<Borrowing> readBorrows;

	//bi-directional many-to-one association to Address
	@ManyToOne
	@JoinColumn(name="addressFk", nullable=false)
	private Address address;

	//bi-directional many-to-one association to Persons_Role
	@OneToMany(mappedBy="person")
	private List<Persons_Role> personsRoles;

	//bi-directional many-to-one association to Reservation
	@OneToMany(mappedBy="person")
	private List<Reservation> reservations;

	//bi-directional many-to-one association to ReturnsB
	@OneToMany(mappedBy="person")
	private List<ReturnsB> returnsBs;

	public Person() {
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public int getBirthCode() {
		return birthCode;
	}

	public void setBirthCode(int birthCode) {
		this.birthCode = birthCode;
	}

	public Date getDateRegistration() {
		return dateRegistration;
	}

	public void setDateRegistration(Date dateRegistration) {
		this.dateRegistration =  dateRegistration;
;
	}
	
	public boolean getIsKnihovnik(){

		boolean flag=false;
		
		List <Persons_Role> j = getPersonsRoles();
		if(j!=null) {
			for(Persons_Role q: j) {
				if(q.getPerson().getLogin().equals(getLogin()) 
						&& q.getRole().getDescription().equals("Knihovnik")) {
					
					flag = true;
					break;
				}	
			}
		}
		
		return flag;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public List<Borrowing> getEmplBorrows() {
		return emplBorrows;
	}

	public void setEmplBorrows(List<Borrowing> emplBorrows) {
		this.emplBorrows = emplBorrows;
	}

	public Borrowing addEmplBorrow(Borrowing emplBorrow) {
		getEmplBorrows().add(emplBorrow);
		emplBorrow.setEmployee(this);

		return emplBorrow;
	}

	public Borrowing removeEmplBorrow(Borrowing emplBorrow) {
		getEmplBorrows().remove(emplBorrow);
		emplBorrow.setEmployee(null);

		return emplBorrow;
	}

	public List<Borrowing> getReadBorrows() {
		return readBorrows;
	}

	public void setReadBorrows(List<Borrowing> readBorrows) {
		this.readBorrows = readBorrows;
	}

	public Borrowing addReadBorrow(Borrowing readBorrow) {
		getReadBorrows().add(readBorrow);
		readBorrow.setReader(this);

		return readBorrow;
	}

	public Borrowing removeReadBorrow(Borrowing readBorrow) {
		getReadBorrows().remove(readBorrow);
		readBorrow.setReader(null);

		return readBorrow;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public List<Persons_Role> getPersonsRoles() {
		return personsRoles;
	}

	public void setPersonsRoles(List<Persons_Role> personsRoles) {
		this.personsRoles = personsRoles;
	}

	public Persons_Role addPersonsRole(Persons_Role personsRole) {
		getPersonsRoles().add(personsRole);
		personsRole.setPerson(this);

		return personsRole;
	}

	public Persons_Role removePersonsRole(Persons_Role personsRole) {
		getPersonsRoles().remove(personsRole);
		personsRole.setPerson(null);

		return personsRole;
	}

	public List<Reservation> getReservations() {
		return reservations;
	}

	public void setReservations(List<Reservation> reservations) {
		this.reservations = reservations;
	}

	public Reservation addReservation(Reservation reservation) {
		getReservations().add(reservation);
		reservation.setPerson(this);

		return reservation;
	}

	public Reservation removeReservation(Reservation reservation) {
		getReservations().remove(reservation);
		reservation.setPerson(null);

		return reservation;
	}

	public List<ReturnsB> getReturnsBs() {
		return returnsBs;
	}

	public void setReturnsBs(List<ReturnsB> returnsBs) {
		this.returnsBs = returnsBs;
	}

	public ReturnsB addReturnsB(ReturnsB returnsB) {
		getReturnsBs().add(returnsB);
		returnsB.setPerson(this);

		return returnsB;
	}

	public ReturnsB removeReturnsB(ReturnsB returnsB) {
		getReturnsBs().remove(returnsB);
		returnsB.setPerson(null);

		return returnsB;
	}

}

WebContent/boss/bossOverview.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Vítej šéfe</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">
	
		<!-- NAVBAR -->
		<ui:include src="navbar.xhtml" />
		
		<!--  SPACE -->
		<b:container>
			<b:row>
				<b:column col-md="6" col-sm="12" style="height: 50px;" />
			</b:row>
		</b:container>

		<!--  FORM-->
	    <b:container>
			<b:column col-xs="12">
				<h:form id="findTitleForm">
				
					<!-- FIRST LINE -->
					<b:column col-xs="12">
	
						<!-- TITLE NAME -->
						<b:column col-xs="2">
						   <h:outputText value="Název:"/>
						</b:column>
						
						<b:column col-xs="4">
						    <b:inputText placeholder="" value="#{findTitleBean.title}"/>
						</b:column>
										
						<!-- ISBN -->
						<b:column col-xs="2">
					   		<h:outputText value="ISBN:"/>
						</b:column>
						
						<b:column col-xs="4">
						    <b:inputText placeholder="" value="#{findTitleBean.isbn}"/>
						</b:column>
		     		</b:column>
		         
		    		<!-- SECOND LINE -->
					<b:column col-xs="12">
					
						<!-- GENRES -->
						<b:column col-xs="2">
						   <h:outputText value="Žánr:"/>
						</b:column>
						<b:column col-xs="4">
						   <b:selectMultiMenu value="#{findTitleBean.genre}">  
							  <f:selectItems 
							  	value="#{genreController.getAll()}" 
							  	var="genre" 
							  	itemValue="#{genre.name}" 
							  	itemLabel="#{genre.name}"/>
						   </b:selectMultiMenu>
						</b:column>
											
						<!-- AUTHORS -->
						<b:column col-xs="2">
						   <h:outputText value="Autor:"/>
						</b:column>
						<b:column col-xs="4">
						   <b:selectMultiMenu value="#{findTitleBean.author}" maxHeight="500">  
							  <f:selectItems value="#{authorController.getAll()}" 
							  	var="author"
							  	itemValue="#{author.fullName}" 
							  	itemLabel="#{author.fullName}"/>
						   </b:selectMultiMenu>
						</b:column>
		     		</b:column>
		     		
		     		<!-- SPACE -->
					<b:column col-xs="12" style="height: 15px;"/>
		     		
		     		<!-- THIRD LINE -->
					<b:column col-xs="12">
					
						<!-- LANGUAGES-->
						<b:column col-xs="2">
						   <h:outputText value="Jazyk:"/>
						</b:column>
						<b:column col-xs="4">
						   <b:selectMultiMenu value="#{findTitleBean.lang}">  
							  <f:selectItem itemValue="cestina" itemLabel="čeština"/>
							  <f:selectItem itemValue="anglictina" itemLabel="angličtina"/>
						   </b:selectMultiMenu>
						</b:column>
											
						<b:column col-xs="2"/>
						<b:column col-xs="4"/>
						
		     		</b:column>
		     	
					<!-- SPACE -->
					<b:column col-xs="12" style="height: 15px;"/>			
		     		
		     		<b:column col-xs="12">
					
						<!-- FIND BUTTON -->
						<b:column col-xs="2" />
						<b:column col-xs="4">
						    <b:commandButton 
						    	update="tabbb" 
						    	icon="search" 
						    	value="Vyhledat" 
						    	look="primary" 
						    	style="width:100%" 
						    	actionListener="#{titleController.findTitles()}" />
						</b:column>
						
						<!-- ADD BUTTON -->
						<b:column col-xs="2" />			
						<b:column col-xs="4">
							<b:commandButton
								value="Přidat" 
								icon="plus" 
								look="success" 
								style="width:100%" 
								action="titleInsertForm" />
						</b:column>	
		     		</b:column>
		     		
		     		<!-- SPACE -->
					<b:column col-xs="12" style="height: 15px;" />				
		     		<b:column col-xs="12">
						<b:column col-xs="2" />
						<b:column col-xs="4" />

						<!-- EDIT BUTTON -->
						<b:column col-xs="2"/>
						<b:column col-xs="4" class="editableCarTable" />
		     		</b:column>
		   		</h:form>
			 </b:column>
   		</b:container>
    	
  		<!-- SPACE -->
		<b:column col-xs="12" style="height: 15px;" />

		<!-- TITLE TABLE LIST, EDIT, REMOVE -->
		<b:container>
			<b:form  id="tabbb">
				<b:dataTable
					class="editableCarTable" 
					value="#{titleController.getFilteredTitles()}" 
					var="title" 
					searching="false" 
					responsive="true">	
							
					<!-- ISBN -->
					<b:dataTableColumn label="Isbn">
	    				<h:outputText value="#{title.isbn}" />
					</b:dataTableColumn>
					
					<!-- NAME -->
					<b:dataTableColumn label="Název">
	    				<h:outputText value="#{title.name}" />
					</b:dataTableColumn>
					
					<!-- AUTHORS-->
					<b:dataTableColumn label="Autoři">
	    				<h:outputText value="#{title.authors}" />
					</b:dataTableColumn>
					
					<!-- GENRES -->
					<b:dataTableColumn label="Žánry">
	    				<h:outputText value="#{title.genres}" />
					</b:dataTableColumn>
					
					<!-- EDITION -->
					<b:dataTableColumn label="Edice">
		    				<h:outputText value="#{title.edition}" />
					</b:dataTableColumn>
					
					<!-- COPIES -->
					<b:dataTableColumn label="Počet výtisků">
	    				<h:outputText value="#{fn:length(title.copies)}" />
					</b:dataTableColumn>
					
					<b:dataTableColumn label="Dostupných">
	    				<h:outputText value="#{libBorrowController.howManyAvaibleCopies(title)}" />
					</b:dataTableColumn>					
					
					<!-- BUTTONS -->
					<b:dataTableColumn label="Akce" orderable="false">
					
						<!-- EDIT BUTTON -->
						<b:commandButton value="Upravit"
							look="info" 
							ajax="true" 
							update="@(.editableCarTable)"
							action="#{titleController.edit(title)}" />
							
						<!-- BORROW BUTTON -->
						<b:commandButton value="Vypůjčit"
							look="primary" 
						  	ajax="true" 
							update="@(.editableCarTable)"
							rendered="#{libBorrowController.isTitleAvaible(title)}"
						  	action="#{borrowingController.prepareBorrow(title)}" />
						  	
						<!-- ADD COPY -->
						<b:commandButton value="Přidat výtisk"
							look="success" 
						  	ajax="true" 
							update="@(.editableCarTable)"
						  	action="#{titleController.addCopy(title)}"/>
						  	
						<!-- REMOVE TITLE -->
						<b:commandButton value="Smazat"
							look="danger" 
						  	ajax="true" 
							update="@(.editableCarTable)"
							rendered="#{libBorrowController.canRemoveTitle(title)}"
						  	action="#{titleController.delete(title)}"/>
						  	
					</b:dataTableColumn>
				</b:dataTable>
			</b:form>
		</b:container>
	</h:body>
</html>

WebContent/boss/navbar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

	<b:navBar brand="Black Books" brandHref="/blackbooks/librarian/librarianOverview.xhtml" inverse="true" fixed="top">
		<b:navbarLinks>
			<b:navLink value="Knihovníci" href="/blackbooks/boss/personsOverview.xhtml"></b:navLink>
			<b:navLink value="Autoři" href="/blackbooks/librarian/titles.xhtml?faces-redirect=true"></b:navLink>
			<b:navLink value="Čtenáři" href="/blackbooks/librarian/management/readers/readers.xhtml?faces-redirect=true"></b:navLink>
			<b:navLink value="Výpůjčky" href="/blackbooks/librarian/books/newauthor.xhtml"></b:navLink>
			<b:navLink value="Rezervace" href="/blackbooks/librarian/newauthor.xhtml?faces-redirect=true"></b:navLink>
			<b:navLink value="Poplatky" href="/blackbooks/librarian/books/genres.xhtml?faces-redirect=true"></b:navLink>
		</b:navbarLinks>

		<h:form method="post" styleClass="navbar-form navbar-right">
			<b:commandButton 
				action="#{accountDAO.logout}"
				value="Odhlásit se" 
				look="success" 
				icon="chevron-right"
				iconAlign="right" />
		</h:form>
	</b:navBar>
</ui:composition>

WebContent/boss/personsOverview.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Seznam knihovníků</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">
	
		<!-- NAVBAR -->
		<ui:include src="/boss/navbar.xhtml" />
		
		<!--  SPACE -->
		<b:container>
			<b:row>
				<b:column col-md="6" col-sm="12" style="height: 50px;" />
			</b:row>
		</b:container>
			
		<b:container>
			<b:form id="readersTab">
				<b:dataTable 
					class="editableCarTable" 
					value="#{personController.getAll()}" 
					var="reader" 
					searching="false" 
					responsive="true">
							
					<!-- IS LIBRARIAN -->
					<b:dataTableColumn label="Knihovník">
	    				<b:selectBooleanCheckbox value="#{reader.isKnihovnik=='true'}" disabled="true" />
					</b:dataTableColumn>
				
					<!-- LOGIN -->
					<b:dataTableColumn label="Login">
	    				<h:outputText value="#{reader.login}" />
					</b:dataTableColumn>
					
					<!-- FIRST NAME -->
					<b:dataTableColumn label="Jméno">
	    				<h:outputText value="#{reader.firstName}" />
					</b:dataTableColumn>
					
					<!-- LAST NAME -->
					<b:dataTableColumn label="Příjmení">
	    				<h:outputText value="#{reader.lastName}" />
					</b:dataTableColumn>
					
					<!-- EMAIL -->
					<b:dataTableColumn label="Email">
	    				<h:outputText value="#{reader.email}" />
					</b:dataTableColumn>
					
					<!-- BIRTH CODE -->
					<b:dataTableColumn label="Rodné číslo">
	    				<h:outputText value="#{reader.birthCode}" />
					</b:dataTableColumn>
					
					<!-- DATE REGISTRATION -->
					<b:dataTableColumn label="Datum registrace">
						<h:outputText value="#{reader.dateRegistration}" /> 
		    				<!--<b:dateTimePicker
											   value="#{reader.dateRegistration}"
											format="YYYY-MM-DD"
											   render-label="true"
											   show-time="false" /> -->
					</b:dataTableColumn>
					
					<!-- BUTTONS -->
					<b:dataTableColumn >
						<f:facet name="header">Delete</f:facet>
						
						<!-- SET LIBRARIAN BUTTON -->
						<b:commandButton 
							value="Knihovnik?" 
							look="warning" 
							action="#{personsRoleController.nastavKnihovnika(reader)}"  
							update="readersTab" />
							
						<!-- EDIT PERSON BUTTON -->
						<b:commandButton 
							value="Editovat" 
							look="info" 
							action="#{personController.edit(reader)}" />
							
					</b:dataTableColumn>
				</b:dataTable>
			</b:form>
		</b:container>
	</h:body>
</html>