src/model/beans/GenreBean.java
package model.beans;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Stateless;
import javax.inject.Named;

import model.entity.Authors_Genre;
import model.entity.Titles_Genre;

@Named
@Stateless
public class GenreBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private int id;
	private String name;
	private List<Authors_Genre> authorsGenres;
	private List<Titles_Genre> titlesGenres;


	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Authors_Genre> getAuthorsGenres() {
		return authorsGenres;
	}

	public void setAuthorsGenres(List<Authors_Genre> authorsGenres) {
		this.authorsGenres = authorsGenres;
	}

	public List<Titles_Genre> getTitlesGenres() {
		return titlesGenres;
	}

	public void setTitlesGenres(List<Titles_Genre> titlesGenres) {
		this.titlesGenres = titlesGenres;
	}
}

src/model/entity/Genre.java
package model.entity;

import java.io.Serializable;
import javax.persistence.*;
import java.util.List;

@Entity
@Table(name="Genres")
@NamedQuery(name="Genre.findAll", query="SELECT g FROM Genre g")
public class Genre implements Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(unique=true, nullable=false)
	private int id;

	@Column(nullable=false, length=20)
	private String name;

	//bi-directional many-to-one association to Authors_Genre
	@OneToMany(mappedBy="genre")
	private List<Authors_Genre> authorsGenres;

	//bi-directional many-to-one association to Titles_Genre
	@OneToMany(mappedBy="genre")
	private List<Titles_Genre> titlesGenres;

	public Genre() {
	}

	public Genre(int id_genre) {
		id = id_genre;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Authors_Genre> getAuthorsGenres() {
		return authorsGenres;
	}

	public void setAuthorsGenres(List<Authors_Genre> authorsGenres) {
		this.authorsGenres = authorsGenres;
	}

	public Authors_Genre addAuthorsGenre(Authors_Genre authorsGenre) {
		getAuthorsGenres().add(authorsGenre);
		authorsGenre.setGenre(this);

		return authorsGenre;
	}

	public Authors_Genre removeAuthorsGenre(Authors_Genre authorsGenre) {
		getAuthorsGenres().remove(authorsGenre);
		authorsGenre.setGenre(null);

		return authorsGenre;
	}

	public List<Titles_Genre> getTitlesGenres() {
		return titlesGenres;
	}

	public void setTitlesGenres(List<Titles_Genre> titlesGenres) {
		this.titlesGenres = titlesGenres;
	}

	public Titles_Genre addTitlesGenre(Titles_Genre titlesGenre) {
		getTitlesGenres().add(titlesGenre);
		titlesGenre.setGenre(this);

		return titlesGenre;
	}

	public Titles_Genre removeTitlesGenre(Titles_Genre titlesGenre) {
		getTitlesGenres().remove(titlesGenre);
		titlesGenre.setGenre(null);

		return titlesGenre;
	}
}

src/controllers/GenreController.java
package controllers;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import model.beans.GenreBean;
import model.entity.Genre;
import model.jpaejb.GenreFacade;

@Named
@SessionScoped
public class GenreController implements Serializable {
	
	private static final long serialVersionUID = 1L;

	@EJB
	GenreFacade genreFacade;
	
	@Inject
	GenreBean genreBean;
	
	public List<Genre> getAll() {
		return genreFacade.findAll();
	}
	
	public int count() {
		return genreFacade.count();
	}
	
	public void delete(Genre genre) {
		if(genre.getAuthorsGenres().isEmpty() && genre.getTitlesGenres().isEmpty())
			genreFacade.remove(genre);
	}
	
	public String add() {
		Genre genre = new Genre();
		
		genre.setName(genreBean.getName());

		genreFacade.create(genre);
		
		return "genres";
	}
	
	public String edit(Genre genre) {

		genreBean.setId(genre.getId());
		genreBean.setName(genre.getName());
		genreBean.setAuthorsGenres(genre.getAuthorsGenres());
		genreBean.setTitlesGenres(genre.getTitlesGenres());
		
		return "genresUpdate";
	}
	
	public String save() {
		Genre genre = new Genre();
	
		genre.setId(genreBean.getId());
		genre.setName(genreBean.getName());
		genre.setAuthorsGenres(genreBean.getAuthorsGenres());
		genre.setTitlesGenres(genreBean.getTitlesGenres());
		
		genreFacade.edit(genre);
		
		return "genres";
	}
}

WebContent/librarian/books/copies.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Správa výtisků</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">
	
		<!-- NAVBAR -->
		<ui:include src="/librarian/navbar.xhtml" />
		
		<!--  SPACE -->
		<b:container>
			<b:row>
				<b:column col-md="6" col-sm="12" style="height: 50px;" />
			</b:row>
		</b:container>
			
		<!-- TABLE OF COPIES -->
		<b:container>
			
				<b:form id="genreTab">
				<!-- INPUTS -->
				<p:panel id="panel" header="Přehled výtisků" style="margin-bottom:10px;">
				    <p:messages id="messages" />
				    <h:panelGrid columns="2" cellpadding="5" style="padding-bottom:10px;">
				    
						<b:dataTable class="editableCarTable"
							value="#{copyController.all}" 
							var="copy" 
							searching="true" 
							multi-column-search="true" 
							responsive="true">
									
								<!-- ISBN -->
								<b:dataTableColumn label="ISBN">
				    				<h:outputText value="#{copy.title.isbn}" />
								</b:dataTableColumn>
								
								<!-- TITLE NAME -->
								<b:dataTableColumn label="Název titulu">
				    				<h:outputText value="#{copy.title.name}" />
				    				
								</b:dataTableColumn>
								<!-- NUMBER OF COPY -->
								<b:dataTableColumn label="Čislo kopie">
				    				<h:outputText value="#{copy.numCopy}" />
								</b:dataTableColumn>
								
								<!-- NOTES -->
								<b:dataTableColumn label="Poznamky">
				    				<b:inputText value="{copy.notes}" placeholder="#{copy.notes}"/>
								</b:dataTableColumn>
								
								<!-- BUTTONS -->
								<b:dataTableColumn >
									<f:facet name="header">Akce</f:facet>
									
									<!-- EDIT BUTTON -->
									<b:commandButton value="Změnit" 
										look="info"
										icon="edit"
										ajax="true" 
										update="@(.editableCarTable)"
										action="#{copyController.edit(copy)}"/>
										
									<!-- DELETE BUTTON -->
									<b:commandButton 
										value="Smazat" 
										look="danger"
										ajax="true" 
										update="@(.editableCarTable)"
										action="#{copyController.delete(copy)}"/>
								</b:dataTableColumn>
						</b:dataTable>
					</h:panelGrid>
				</p:panel>
			</b:form>
		</b:container>
	</h:body>
</html>

WebContent/librarian/books/copiesCreate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Vytvořit kopii</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">

		<!-- NAVBAR -->
		<ui:include src="/librarian/navbar.xhtml" />
		
		<!-- FORM -->
		<b:container>
			<b:form id="genreTab">
			
				<!-- ISBN -->
				<h:outputLabel for="isbnList" value="Vyberte ISBN:" />
				<b:selectOneMenu id="isbnList" value="#{copyBean.title}">
		            <f:selectItems
		            	value="#{titleController.getAll()}" 
		            	var="title" 
		            	itemValue="#{title}" 
		            	itemLabel="#{title.isbn}" />
		        </b:selectOneMenu>
		        
		        <!-- NAME -->
				<b:inputText value="#{genreBean.name}"/>
				
				<!-- BUTTONS -->
				<h:commandButton
					action="#{genreController.add}" 
					value="Přidat" />
				
				<h:commandButton
					action="#{genreController.save}"
					value="Upravit" />
					
			</b:form>
		</b:container>
	</h:body>
</html>

WebContent/librarian/books/copiesUpdate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Uprava</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">
		
		<!-- NAVBAR -->
		<ui:include src="/librarian/navbar.xhtml" />
		
		<!-- FORM -->
		<b:form id="genreTab">
				
			<h:outputText value="#{copyBean.title.isbn}" />
			<h:outputText value="#{copyBean.title.name}" />
			<b:inputText value="#{copyBean.title}" />
			<b:inputText value="#{copyBean.notes}" />
			
			<h:commandButton
				action="#{genreController.add}"
				value="Přidat" />
				
			<h:commandButton 
				action="#{genreController.save}" 
				value="Upravit" />
		</b:form>
	</h:body>
</html>

WebContent/librarian/books/genres.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Vitej knihovniku</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">
	
		<!-- NAVBAR -->
		<ui:include src="/librarian/navbar.xhtml" />
		
		<!-- FORM -->
		<b:form id="genreTab">
			<b:dataTable
				class="editableCarTable" 
				value="#{genreController.getAll()}" 
				var="genre" 
				searching="false" 
				responsive="true">	
						
				<!-- GENRE NAME -->
				<b:dataTableColumn label="Název">
    				<h:outputText value="#{genre.name}" />
				</b:dataTableColumn>
				
				<!-- BUTTONS -->
				<b:dataTableColumn label="Akce">
				
					<!-- SAVE BUTTONS -->
					<b:commandButton 
						value="Uložit" 
						look="warning" 
						action="#{genreController.edit(genre)}" />
						
					<!-- DELETE BUTTONS -->
					<h:commandLink 
						value="Delete" 
						action="#{genreController.delete(genre)}" 
						ajax="true" 
						update="@(.editableCarTable)" />
						
				</b:dataTableColumn>
			</b:dataTable>
		</b:form>	   
	</h:body>
</html>

WebContent/librarian/books/genresUpdate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<!-- TODO -->
	
	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Uprava</title>
	</h:head>
	
	<h:body style="padding-top: 50px; padding-bottom: 20px;">
	
		<!-- NAVBAR -->
		<ui:include src="/librarian/navbar.xhtml" />
		
		<!-- FORM -->
		<b:form id="genreTab">
			<b:inputText value="#{genreBean.id}"/>
			<b:inputText value="#{genreBean.name}"/>
			<h:commandButton action="#{genreController.add}" value="Přidat"></h:commandButton>
			<h:commandButton action="#{genreController.save}" value="Upravit"></h:commandButton>
		</b:form>
	</h:body>
</html>